apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-deployment
spec:
  selector:
    matchLabels:
      app: time
  replicas: 2
  template:
    metadata:
      labels:
        app: time
    spec:
      containers:
      - name: time
        image: roshan02/time:latest
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: time
  labels:
    run: time
spec:
  type: NodePort
  ports:
  - port: 5000
   
  selector:
    app: time